currencies = [
  { code: "AED", country: "United Arab Emirates" },
  { code: "AFN", country: "Afghanistan" },
  { code: "ALL", country: "Albania" },
  { code: "AMD", country: "Armenia" },
  { code: "ANG", country: "Netherlands Antilles" },
  { code: "AOA", country: "Angola" },
  { code: "ARS", country: "Argentina" },
  { code: "AUD", country: "Australia" },
  { code: "AWG", country: "Aruba" },
  { code: "AZN", country: "Azerbaijan" },
  { code: "BAM", country: "Bosnia and Herzegovina" },
  { code: "BBD", country: "Barbados" },
  { code: "BDT", country: "Bangladesh" },
  { code: "BGN", country: "Bulgaria" },
  { code: "BHD", country: "Bahrain" },
  { code: "BIF", country: "Burundi" },
  { code: "BMD", country: "Bermuda" },
  { code: "BND", country: "Brunei Darussalam" },
  { code: "BOB", country: "Bolivia" },
  { code: "BRL", country: "Brazil" },
  { code: "BSD", country: "Bahamas" },
  { code: "BTC", country: "Bitcoin (Cryptocurrency)" },
  { code: "BTN", country: "Bhutan" },
  { code: "BWP", country: "Botswana" },
  { code: "BYN", country: "Belarus" },
  { code: "BZD", country: "Belize" },
  { code: "CAD", country: "Canada" },
  { code: "CDF", country: "Congo (Democratic Republic)" },
  { code: "CHF", country: "Switzerland" },
  { code: "CLF", country: "Chile (Unidad de Fomento)" },
  { code: "CLP", country: "Chile" },
  { code: "CNY", country: "China" },
  { code: "COP", country: "Colombia" },
  { code: "CRC", country: "Costa Rica" },
  { code: "CUC", country: "Cuba (Convertible Peso)" },
  { code: "CUP", country: "Cuba" },
  { code: "CVE", country: "Cape Verde" },
  { code: "CZK", country: "Czech Republic" },
  { code: "DJF", country: "Djibouti" },
  { code: "DKK", country: "Denmark" },
  { code: "DOP", country: "Dominican Republic" },
  { code: "DZD", country: "Algeria" },
  { code: "EGP", country: "Egypt" },
  { code: "ERN", country: "Eritrea" },
  { code: "ETB", country: "Ethiopia" },
  { code: "EUR", country: "European Union" },
  { code: "FJD", country: "Fiji" },
  { code: "FKP", country: "Falkland Islands" },
  { code: "GBP", country: "United Kingdom" },
  { code: "GEL", country: "Georgia" },
  { code: "GGP", country: "Guernsey" },
  { code: "GHS", country: "Ghana" },
  { code: "GIP", country: "Gibraltar" },
  { code: "GMD", country: "Gambia" },
  { code: "GNF", country: "Guinea" },
  { code: "GTQ", country: "Guatemala" },
  { code: "GYD", country: "Guyana" },
  { code: "HKD", country: "Hong Kong" },
  { code: "HNL", country: "Honduras" },
  { code: "HRK", country: "Croatia" },
  { code: "HTG", country: "Haiti" },
  { code: "HUF", country: "Hungary" },
  { code: "IDR", country: "Indonesia" },
  { code: "ILS", country: "Israel" },
  { code: "IMP", country: "Isle of Man" },
  { code: "INR", country: "India" },
  { code: "IQD", country: "Iraq" },
  { code: "IRR", country: "Iran" },
  { code: "ISK", country: "Iceland" },
  { code: "JEP", country: "Jersey" },
  { code: "JMD", country: "Jamaica" },
  { code: "JOD", country: "Jordan" },
  { code: "JPY", country: "Japan" },
  { code: "KES", country: "Kenya" },
  { code: "KGS", country: "Kyrgyzstan" },
  { code: "KHR", country: "Cambodia" },
  { code: "KMF", country: "Comoros" },
  { code: "KPW", country: "North Korea" },
  { code: "KRW", country: "South Korea" },
  { code: "KWD", country: "Kuwait" },
  { code: "KYD", country: "Cayman Islands" },
  { code: "KZT", country: "Kazakhstan" },
  { code: "LAK", country: "Laos" },
  { code: "LBP", country: "Lebanon" },
  { code: "LKR", country: "Sri Lanka" },
  { code: "LRD", country: "Liberia" },
  { code: "LSL", country: "Lesotho" },
  { code: "LYD", country: "Libya" },
  { code: "MAD", country: "Morocco" },
  { code: "MDL", country: "Moldova" },
  { code: "MGA", country: "Madagascar" },
  { code: "MKD", country: "North Macedonia" },
  { code: "MMK", country: "Myanmar" },
  { code: "MNT", country: "Mongolia" },
  { code: "MOP", country: "Macau" },
  { code: "MRU", country: "Mauritania" },
  { code: "MUR", country: "Mauritius" },
  { code: "MVR", country: "Maldives" },
  { code: "MWK", country: "Malawi" },
  { code: "MXN", country: "Mexico" },
  { code: "MYR", country: "Malaysia" },
  { code: "MZN", country: "Mozambique" },
  { code: "NAD", country: "Namibia" },
  { code: "NGN", country: "Nigeria" },
  { code: "NIO", country: "Nicaragua" },
  { code: "NOK", country: "Norway" },
  { code: "NPR", country: "Nepal" },
  { code: "NZD", country: "New Zealand" },
  { code: "OMR", country: "Oman" },
  { code: "PAB", country: "Panama" },
  { code: "PEN", country: "Peru" },
  { code: "PGK", country: "Papua New Guinea" },
  { code: "PHP", country: "Philippines" },
  { code: "PKR", country: "Pakistan" },
  { code: "PLN", country: "Poland" },
  { code: "PYG", country: "Paraguay" },
  { code: "QAR", country: "Qatar" },
  { code: "RON", country: "Romania" },
  { code: "RSD", country: "Serbia" },
  { code: "RUB", country: "Russia" },
  { code: "RWF", country: "Rwanda" },
  { code: "SAR", country: "Saudi Arabia" },
  { code: "SBD", country: "Solomon Islands" },
  { code: "SCR", country: "Seychelles" },
  { code: "SDG", country: "Sudan" },
  { code: "SEK", country: "Sweden" },
  { code: "SGD", country: "Singapore" },
  { code: "SHP", country: "Saint Helena" },
  { code: "SLL", country: "Sierra Leone" },
  { code: "SOS", country: "Somalia" },
  { code: "SRD", country: "Suriname" },
  { code: "SSP", country: "South Sudan" },
  { code: "STD", country: "São Tomé and Príncipe" },
  { code: "STN", country: "São Tomé and Príncipe (new)" },
  { code: "SVC", country: "El Salvador" },
  { code: "SYP", country: "Syria" },
  { code: "SZL", country: "Eswatini" },
  { code: "THB", country: "Thailand" },
  { code: "TJS", country: "Tajikistan" },
  { code: "TMT", country: "Turkmenistan" },
  { code: "TND", country: "Tunisia" },
  { code: "TOP", country: "Tonga" },
  { code: "TRY", country: "Turkey" },
  { code: "TTD", country: "Trinidad and Tobago" },
  { code: "TWD", country: "Taiwan" },
  { code: "TZS", country: "Tanzania" },
  { code: "UAH", country: "Ukraine" },
  { code: "UGX", country: "Uganda" },
  { code: "USD", country: "United States" },
  { code: "UYU", country: "Uruguay" },
  { code: "UZS", country: "Uzbekistan" },
  { code: "VEF", country: "Venezuela" },
  { code: "VES", country: "Venezuela (new)" },
  { code: "VND", country: "Vietnam" },
  { code: "VUV", country: "Vanuatu" },
  { code: "WST", country: "Samoa" },
  { code: "XAF", country: "Central African States" },
  { code: "XAG", country: "Silver (Commodity)" },
  { code: "XAU", country: "Gold (Commodity)" },
  { code: "XCD", country: "Eastern Caribbean" },
  { code: "XDR", country: "International Monetary Fund (IMF)" },
  { code: "XOF", country: "West African States" },
  { code: "XPD", country: "Palladium (Commodity)" },
  { code: "XPF", country: "French Pacific Territories" },
  { code: "XPT", country: "Platinum (Commodity)" },
  { code: "YER", country: "Yemen" },
  { code: "ZAR", country: "South Africa" },
  { code: "ZMW", country: "Zambia" },
  { code: "ZWL", country: "Zimbabwe" },
];
